{"uuid": "a3f2d4e9-c940-4e7a-af5b-bf4d7b3fe73c", "children": ["4b36a830-e74b-428e-b18a-36fcf868659a"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: Could not reach host. Are you offline?\n", "trace": "  File \"/Users/macbook/Documents/Practicum/Sprint_6/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/Users/macbook/Documents/Practicum/Sprint_6/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"/Users/macbook/Documents/Practicum/Sprint_6/.venv/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/macbook/Documents/Practicum/Sprint_6/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/macbook/Documents/Practicum/Sprint_6/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/macbook/Documents/Practicum/Sprint_6/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/macbook/Documents/Practicum/Sprint_6/conftest.py\", line 8, in driver\n    driver = webdriver.Firefox(executable_path=GeckoDriverManager().install())\n                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"/Users/macbook/Documents/Practicum/Sprint_6/.venv/lib/python3.13/site-packages/webdriver_manager/firefox.py\", line 39, in install\n    driver_path = self._get_driver_binary_path(self.driver)\n  File \"/Users/macbook/Documents/Practicum/Sprint_6/.venv/lib/python3.13/site-packages/webdriver_manager/core/manager.py\", line 35, in _get_driver_binary_path\n    binary_path = self._cache_manager.find_driver(driver)\n  File \"/Users/macbook/Documents/Practicum/Sprint_6/.venv/lib/python3.13/site-packages/webdriver_manager/core/driver_cache.py\", line 107, in find_driver\n    driver_version = self.get_cache_key_driver_version(driver)\n  File \"/Users/macbook/Documents/Practicum/Sprint_6/.venv/lib/python3.13/site-packages/webdriver_manager/core/driver_cache.py\", line 154, in get_cache_key_driver_version\n    return driver.get_driver_version_to_download()\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"/Users/macbook/Documents/Practicum/Sprint_6/.venv/lib/python3.13/site-packages/webdriver_manager/core/driver.py\", line 48, in get_driver_version_to_download\n    return self.get_latest_release_version()\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"/Users/macbook/Documents/Practicum/Sprint_6/.venv/lib/python3.13/site-packages/webdriver_manager/drivers/firefox.py\", line 29, in get_latest_release_version\n    resp = self._http_client.get(\n        url=self.latest_release_url,\n        headers=self.auth_header\n    )\n  File \"/Users/macbook/Documents/Practicum/Sprint_6/.venv/lib/python3.13/site-packages/webdriver_manager/core/http.py\", line 35, in get\n    raise exceptions.ConnectionError(f\"Could not reach host. Are you offline?\")\n"}, "start": 1748958551891, "stop": 1748958582071}], "start": 1748958551891, "stop": 1748958582195}